- name: Creating directory and copying passwd file
  hosts: 172.31.19.144
  tasks:
   - name: creating directory
     file:
      name: newdir2
      state: directory
   - name: copying passwd file
     copy:
      src: /etc/passwd
      dest: newdir2
